networks:
  appnet:
    driver: bridge

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python
    depends_on:
      - db
      - mlflow
    networks:
      - appnet
    volumes:
      - data_volume:/workdir/scripts/data
      - mlflow_artifacts:/workdir/artifacts
    env_file:
      - .env
    command: python scripts/main.py
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  db:
    image: postgres:13
    container_name: postgres-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - appnet
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - data_volume:/data

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow-server
    ports:
      - "5000:5000"
    networks:
      - appnet
    volumes:
      - mlflow_volume:/mlruns
      - mlflow_artifacts:/mlflow/artifacts
    environment:
      - MLFLOW_ARTIFACT_URI=/mlflow/artifacts

volumes:
  postgres_data:
  data_volume:
  mlflow_volume:
  mlflow_artifacts:
